server:
  port: 8081

spring:
  application:
    name: order-service

payment:
  service:
    url: ${PAYMENT_SERVICE_URL:http://localhost:8082}

logging:
  file:
    name: ${user.home}/microservices-logs/order-service/order-service.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level traceId=%X{traceId} %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level traceId=%X{traceId} %logger{36} - %msg%n"
